name: SinusAC
version: '1.2.0'
main: ru.dtpsaa.sinusac.SinusAC
api-version: '1.16'
softdepend: [floodgate]

commands:
  sinusac:
    description: Manage SinusAC AntiCheat
    usage: /sinusac <подкоманда>
    aliases: [sac]
    permission: sinusac.admin

permissions:
  sinusac.admin:
    description: Full access to SinusAC commands
    default: op
    children:
      sinusac.alerts: true
      sinusac.holo: true

  sinusac.alerts:
    description: Receive SinusAC detection alerts
    default: op

  sinusac.holo:
    description: Toggle personal SinusAC holograms
    default: op

  anticheat.bypass:
    description: Bypass all SinusAC checks
    default: false
